version: '2.2'
services:
  dev_laravel:
    image: laravel:latest
    build: "./"
    tty: true
    container_name: dev_laravel
    ports: 
      - 8089:80
    restart: always
    environment:
      DB_HOST: dev_mysql
      DB_USERNAME: dev_laravel
      DB_DATABASE: dev_laravel
      DB_PASSWORD: dev_laravel_pass
      VIRTUAL_HOST: dev.example.com
      SELF_SIGNED_HOST: dev.example.com
      APP_URL: https://dev.example.com
      APP_ENV: local
      APP_DEBUG: 1
      VIRTUAL_PORT: 80
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ".:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/custom.ini"
    mem_limit: 2G
    
networks:
  default:
    name: proxy
    external: true